// Location data and API for countries, states, and cities
// This uses a public API for location data

export interface Country {
  code: string;
  name: string;
}

export interface State {
  code: string;
  name: string;
  countryCode: string;
}

export interface City {
  name: string;
  stateCode: string;
  countryCode: string;
}

// Popular countries list
export const popularCountries: Country[] = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "KP", name: "North Korea" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

// Sample states/provinces data (this would ideally come from an API)
export const statesData: Record<string, State[]> = {
  US: [
    { code: "AL", name: "Alabama", countryCode: "US" },
    { code: "AK", name: "Alaska", countryCode: "US" },
    { code: "AZ", name: "Arizona", countryCode: "US" },
    { code: "AR", name: "Arkansas", countryCode: "US" },
    { code: "CA", name: "California", countryCode: "US" },
    { code: "CO", name: "Colorado", countryCode: "US" },
    { code: "CT", name: "Connecticut", countryCode: "US" },
    { code: "DE", name: "Delaware", countryCode: "US" },
    { code: "FL", name: "Florida", countryCode: "US" },
    { code: "GA", name: "Georgia", countryCode: "US" },
    { code: "HI", name: "Hawaii", countryCode: "US" },
    { code: "ID", name: "Idaho", countryCode: "US" },
    { code: "IL", name: "Illinois", countryCode: "US" },
    { code: "IN", name: "Indiana", countryCode: "US" },
    { code: "IA", name: "Iowa", countryCode: "US" },
    { code: "KS", name: "Kansas", countryCode: "US" },
    { code: "KY", name: "Kentucky", countryCode: "US" },
    { code: "LA", name: "Louisiana", countryCode: "US" },
    { code: "ME", name: "Maine", countryCode: "US" },
    { code: "MD", name: "Maryland", countryCode: "US" },
    { code: "MA", name: "Massachusetts", countryCode: "US" },
    { code: "MI", name: "Michigan", countryCode: "US" },
    { code: "MN", name: "Minnesota", countryCode: "US" },
    { code: "MS", name: "Mississippi", countryCode: "US" },
    { code: "MO", name: "Missouri", countryCode: "US" },
    { code: "MT", name: "Montana", countryCode: "US" },
    { code: "NE", name: "Nebraska", countryCode: "US" },
    { code: "NV", name: "Nevada", countryCode: "US" },
    { code: "NH", name: "New Hampshire", countryCode: "US" },
    { code: "NJ", name: "New Jersey", countryCode: "US" },
    { code: "NM", name: "New Mexico", countryCode: "US" },
    { code: "NY", name: "New York", countryCode: "US" },
    { code: "NC", name: "North Carolina", countryCode: "US" },
    { code: "ND", name: "North Dakota", countryCode: "US" },
    { code: "OH", name: "Ohio", countryCode: "US" },
    { code: "OK", name: "Oklahoma", countryCode: "US" },
    { code: "OR", name: "Oregon", countryCode: "US" },
    { code: "PA", name: "Pennsylvania", countryCode: "US" },
    { code: "RI", name: "Rhode Island", countryCode: "US" },
    { code: "SC", name: "South Carolina", countryCode: "US" },
    { code: "SD", name: "South Dakota", countryCode: "US" },
    { code: "TN", name: "Tennessee", countryCode: "US" },
    { code: "TX", name: "Texas", countryCode: "US" },
    { code: "UT", name: "Utah", countryCode: "US" },
    { code: "VT", name: "Vermont", countryCode: "US" },
    { code: "VA", name: "Virginia", countryCode: "US" },
    { code: "WA", name: "Washington", countryCode: "US" },
    { code: "WV", name: "West Virginia", countryCode: "US" },
    { code: "WI", name: "Wisconsin", countryCode: "US" },
    { code: "WY", name: "Wyoming", countryCode: "US" },
  ],
  CA: [
    { code: "AB", name: "Alberta", countryCode: "CA" },
    { code: "BC", name: "British Columbia", countryCode: "CA" },
    { code: "MB", name: "Manitoba", countryCode: "CA" },
    { code: "NB", name: "New Brunswick", countryCode: "CA" },
    { code: "NL", name: "Newfoundland and Labrador", countryCode: "CA" },
    { code: "NS", name: "Nova Scotia", countryCode: "CA" },
    { code: "ON", name: "Ontario", countryCode: "CA" },
    { code: "PE", name: "Prince Edward Island", countryCode: "CA" },
    { code: "QC", name: "Quebec", countryCode: "CA" },
    { code: "SK", name: "Saskatchewan", countryCode: "CA" },
    { code: "NT", name: "Northwest Territories", countryCode: "CA" },
    { code: "NU", name: "Nunavut", countryCode: "CA" },
    { code: "YT", name: "Yukon", countryCode: "CA" },
  ],
  GB: [
    { code: "ENG", name: "England", countryCode: "GB" },
    { code: "SCT", name: "Scotland", countryCode: "GB" },
    { code: "WLS", name: "Wales", countryCode: "GB" },
    { code: "NIR", name: "Northern Ireland", countryCode: "GB" },
  ],
  IN: [
    { code: "AN", name: "Andaman and Nicobar Islands", countryCode: "IN" },
    { code: "AP", name: "Andhra Pradesh", countryCode: "IN" },
    { code: "AR", name: "Arunachal Pradesh", countryCode: "IN" },
    { code: "AS", name: "Assam", countryCode: "IN" },
    { code: "BR", name: "Bihar", countryCode: "IN" },
    { code: "CH", name: "Chandigarh", countryCode: "IN" },
    { code: "CT", name: "Chhattisgarh", countryCode: "IN" },
    { code: "DL", name: "Delhi", countryCode: "IN" },
    { code: "GA", name: "Goa", countryCode: "IN" },
    { code: "GJ", name: "Gujarat", countryCode: "IN" },
    { code: "HR", name: "Haryana", countryCode: "IN" },
    { code: "HP", name: "Himachal Pradesh", countryCode: "IN" },
    { code: "JK", name: "Jammu and Kashmir", countryCode: "IN" },
    { code: "JH", name: "Jharkhand", countryCode: "IN" },
    { code: "KA", name: "Karnataka", countryCode: "IN" },
    { code: "KL", name: "Kerala", countryCode: "IN" },
    { code: "MP", name: "Madhya Pradesh", countryCode: "IN" },
    { code: "MH", name: "Maharashtra", countryCode: "IN" },
    { code: "MN", name: "Manipur", countryCode: "IN" },
    { code: "ML", name: "Meghalaya", countryCode: "IN" },
    { code: "MZ", name: "Mizoram", countryCode: "IN" },
    { code: "NL", name: "Nagaland", countryCode: "IN" },
    { code: "OR", name: "Odisha", countryCode: "IN" },
    { code: "PY", name: "Puducherry", countryCode: "IN" },
    { code: "PB", name: "Punjab", countryCode: "IN" },
    { code: "RJ", name: "Rajasthan", countryCode: "IN" },
    { code: "SK", name: "Sikkim", countryCode: "IN" },
    { code: "TN", name: "Tamil Nadu", countryCode: "IN" },
    { code: "TG", name: "Telangana", countryCode: "IN" },
    { code: "TR", name: "Tripura", countryCode: "IN" },
    { code: "UP", name: "Uttar Pradesh", countryCode: "IN" },
    { code: "UT", name: "Uttarakhand", countryCode: "IN" },
    { code: "WB", name: "West Bengal", countryCode: "IN" },
  ],
  AU: [
    { code: "NSW", name: "New South Wales", countryCode: "AU" },
    { code: "QLD", name: "Queensland", countryCode: "AU" },
    { code: "SA", name: "South Australia", countryCode: "AU" },
    { code: "TAS", name: "Tasmania", countryCode: "AU" },
    { code: "VIC", name: "Victoria", countryCode: "AU" },
    { code: "WA", name: "Western Australia", countryCode: "AU" },
    { code: "ACT", name: "Australian Capital Territory", countryCode: "AU" },
    { code: "NT", name: "Northern Territory", countryCode: "AU" },
  ],
  DE: [
    { code: "BW", name: "Baden-Württemberg", countryCode: "DE" },
    { code: "BY", name: "Bavaria", countryCode: "DE" },
    { code: "BE", name: "Berlin", countryCode: "DE" },
    { code: "BB", name: "Brandenburg", countryCode: "DE" },
    { code: "HB", name: "Bremen", countryCode: "DE" },
    { code: "HH", name: "Hamburg", countryCode: "DE" },
    { code: "HE", name: "Hesse", countryCode: "DE" },
    { code: "MV", name: "Mecklenburg-Vorpommern", countryCode: "DE" },
    { code: "NI", name: "Lower Saxony", countryCode: "DE" },
    { code: "NW", name: "North Rhine-Westphalia", countryCode: "DE" },
    { code: "RP", name: "Rhineland-Palatinate", countryCode: "DE" },
    { code: "SL", name: "Saarland", countryCode: "DE" },
    { code: "SN", name: "Saxony", countryCode: "DE" },
    { code: "ST", name: "Saxony-Anhalt", countryCode: "DE" },
    { code: "SH", name: "Schleswig-Holstein", countryCode: "DE" },
    { code: "TH", name: "Thuringia", countryCode: "DE" },
  ],
  FR: [
    { code: "ARA", name: "Auvergne-Rhône-Alpes", countryCode: "FR" },
    { code: "BFC", name: "Bourgogne-Franche-Comté", countryCode: "FR" },
    { code: "BRE", name: "Brittany", countryCode: "FR" },
    { code: "CVL", name: "Centre-Val de Loire", countryCode: "FR" },
    { code: "COR", name: "Corsica", countryCode: "FR" },
    { code: "GES", name: "Grand Est", countryCode: "FR" },
    { code: "HDF", name: "Hauts-de-France", countryCode: "FR" },
    { code: "IDF", name: "Île-de-France", countryCode: "FR" },
    { code: "NOR", name: "Normandy", countryCode: "FR" },
    { code: "NAQ", name: "Nouvelle-Aquitaine", countryCode: "FR" },
    { code: "OCC", name: "Occitanie", countryCode: "FR" },
    { code: "PDL", name: "Pays de la Loire", countryCode: "FR" },
    { code: "PAC", name: "Provence-Alpes-Côte d'Azur", countryCode: "FR" },
  ],
  BR: [
    { code: "AC", name: "Acre", countryCode: "BR" },
    { code: "AL", name: "Alagoas", countryCode: "BR" },
    { code: "AP", name: "Amapá", countryCode: "BR" },
    { code: "AM", name: "Amazonas", countryCode: "BR" },
    { code: "BA", name: "Bahia", countryCode: "BR" },
    { code: "CE", name: "Ceará", countryCode: "BR" },
    { code: "DF", name: "Federal District", countryCode: "BR" },
    { code: "ES", name: "Espírito Santo", countryCode: "BR" },
    { code: "GO", name: "Goiás", countryCode: "BR" },
    { code: "MA", name: "Maranhão", countryCode: "BR" },
    { code: "MT", name: "Mato Grosso", countryCode: "BR" },
    { code: "MS", name: "Mato Grosso do Sul", countryCode: "BR" },
    { code: "MG", name: "Minas Gerais", countryCode: "BR" },
    { code: "PA", name: "Pará", countryCode: "BR" },
    { code: "PB", name: "Paraíba", countryCode: "BR" },
    { code: "PR", name: "Paraná", countryCode: "BR" },
    { code: "PE", name: "Pernambuco", countryCode: "BR" },
    { code: "PI", name: "Piauí", countryCode: "BR" },
    { code: "RJ", name: "Rio de Janeiro", countryCode: "BR" },
    { code: "RN", name: "Rio Grande do Norte", countryCode: "BR" },
    { code: "RS", name: "Rio Grande do Sul", countryCode: "BR" },
    { code: "RO", name: "Rondônia", countryCode: "BR" },
    { code: "RR", name: "Roraima", countryCode: "BR" },
    { code: "SC", name: "Santa Catarina", countryCode: "BR" },
    { code: "SP", name: "São Paulo", countryCode: "BR" },
    { code: "SE", name: "Sergipe", countryCode: "BR" },
    { code: "TO", name: "Tocantins", countryCode: "BR" },
  ],
  MX: [
    { code: "AGU", name: "Aguascalientes", countryCode: "MX" },
    { code: "BCN", name: "Baja California", countryCode: "MX" },
    { code: "BCS", name: "Baja California Sur", countryCode: "MX" },
    { code: "CAM", name: "Campeche", countryCode: "MX" },
    { code: "CHP", name: "Chiapas", countryCode: "MX" },
    { code: "CHH", name: "Chihuahua", countryCode: "MX" },
    { code: "COA", name: "Coahuila", countryCode: "MX" },
    { code: "COL", name: "Colima", countryCode: "MX" },
    { code: "DUR", name: "Durango", countryCode: "MX" },
    { code: "GUA", name: "Guanajuato", countryCode: "MX" },
    { code: "GRO", name: "Guerrero", countryCode: "MX" },
    { code: "HID", name: "Hidalgo", countryCode: "MX" },
    { code: "JAL", name: "Jalisco", countryCode: "MX" },
    { code: "MEX", name: "Mexico State", countryCode: "MX" },
    { code: "MIC", name: "Michoacán", countryCode: "MX" },
    { code: "MOR", name: "Morelos", countryCode: "MX" },
    { code: "NAY", name: "Nayarit", countryCode: "MX" },
    { code: "NLE", name: "Nuevo León", countryCode: "MX" },
    { code: "OAX", name: "Oaxaca", countryCode: "MX" },
    { code: "PUE", name: "Puebla", countryCode: "MX" },
    { code: "QUE", name: "Querétaro", countryCode: "MX" },
    { code: "ROO", name: "Quintana Roo", countryCode: "MX" },
    { code: "SLP", name: "San Luis Potosí", countryCode: "MX" },
    { code: "SIN", name: "Sinaloa", countryCode: "MX" },
    { code: "SON", name: "Sonora", countryCode: "MX" },
    { code: "TAB", name: "Tabasco", countryCode: "MX" },
    { code: "TAM", name: "Tamaulipas", countryCode: "MX" },
    { code: "TLA", name: "Tlaxcala", countryCode: "MX" },
    { code: "VER", name: "Veracruz", countryCode: "MX" },
    { code: "YUC", name: "Yucatán", countryCode: "MX" },
    { code: "ZAC", name: "Zacatecas", countryCode: "MX" },
    { code: "CMX", name: "Mexico City", countryCode: "MX" },
  ],
  CN: [
    { code: "AH", name: "Anhui", countryCode: "CN" },
    { code: "BJ", name: "Beijing", countryCode: "CN" },
    { code: "CQ", name: "Chongqing", countryCode: "CN" },
    { code: "FJ", name: "Fujian", countryCode: "CN" },
    { code: "GS", name: "Gansu", countryCode: "CN" },
    { code: "GD", name: "Guangdong", countryCode: "CN" },
    { code: "GX", name: "Guangxi", countryCode: "CN" },
    { code: "GZ", name: "Guizhou", countryCode: "CN" },
    { code: "HI", name: "Hainan", countryCode: "CN" },
    { code: "HE", name: "Hebei", countryCode: "CN" },
    { code: "HL", name: "Heilongjiang", countryCode: "CN" },
    { code: "HA", name: "Henan", countryCode: "CN" },
    { code: "HB", name: "Hubei", countryCode: "CN" },
    { code: "HN", name: "Hunan", countryCode: "CN" },
    { code: "JS", name: "Jiangsu", countryCode: "CN" },
    { code: "JX", name: "Jiangxi", countryCode: "CN" },
    { code: "JL", name: "Jilin", countryCode: "CN" },
    { code: "LN", name: "Liaoning", countryCode: "CN" },
    { code: "NM", name: "Inner Mongolia", countryCode: "CN" },
    { code: "NX", name: "Ningxia", countryCode: "CN" },
    { code: "QH", name: "Qinghai", countryCode: "CN" },
    { code: "SN", name: "Shaanxi", countryCode: "CN" },
    { code: "SD", name: "Shandong", countryCode: "CN" },
    { code: "SH", name: "Shanghai", countryCode: "CN" },
    { code: "SX", name: "Shanxi", countryCode: "CN" },
    { code: "SC", name: "Sichuan", countryCode: "CN" },
    { code: "TJ", name: "Tianjin", countryCode: "CN" },
    { code: "XJ", name: "Xinjiang", countryCode: "CN" },
    { code: "XZ", name: "Tibet", countryCode: "CN" },
    { code: "YN", name: "Yunnan", countryCode: "CN" },
    { code: "ZJ", name: "Zhejiang", countryCode: "CN" },
  ],
  JP: [
    { code: "01", name: "Hokkaido", countryCode: "JP" },
    { code: "02", name: "Aomori", countryCode: "JP" },
    { code: "03", name: "Iwate", countryCode: "JP" },
    { code: "04", name: "Miyagi", countryCode: "JP" },
    { code: "05", name: "Akita", countryCode: "JP" },
    { code: "06", name: "Yamagata", countryCode: "JP" },
    { code: "07", name: "Fukushima", countryCode: "JP" },
    { code: "08", name: "Ibaraki", countryCode: "JP" },
    { code: "09", name: "Tochigi", countryCode: "JP" },
    { code: "10", name: "Gunma", countryCode: "JP" },
    { code: "11", name: "Saitama", countryCode: "JP" },
    { code: "12", name: "Chiba", countryCode: "JP" },
    { code: "13", name: "Tokyo", countryCode: "JP" },
    { code: "14", name: "Kanagawa", countryCode: "JP" },
    { code: "15", name: "Niigata", countryCode: "JP" },
    { code: "16", name: "Toyama", countryCode: "JP" },
    { code: "17", name: "Ishikawa", countryCode: "JP" },
    { code: "18", name: "Fukui", countryCode: "JP" },
    { code: "19", name: "Yamanashi", countryCode: "JP" },
    { code: "20", name: "Nagano", countryCode: "JP" },
    { code: "21", name: "Gifu", countryCode: "JP" },
    { code: "22", name: "Shizuoka", countryCode: "JP" },
    { code: "23", name: "Aichi", countryCode: "JP" },
    { code: "24", name: "Mie", countryCode: "JP" },
    { code: "25", name: "Shiga", countryCode: "JP" },
    { code: "26", name: "Kyoto", countryCode: "JP" },
    { code: "27", name: "Osaka", countryCode: "JP" },
    { code: "28", name: "Hyogo", countryCode: "JP" },
    { code: "29", name: "Nara", countryCode: "JP" },
    { code: "30", name: "Wakayama", countryCode: "JP" },
    { code: "31", name: "Tottori", countryCode: "JP" },
    { code: "32", name: "Shimane", countryCode: "JP" },
    { code: "33", name: "Okayama", countryCode: "JP" },
    { code: "34", name: "Hiroshima", countryCode: "JP" },
    { code: "35", name: "Yamaguchi", countryCode: "JP" },
    { code: "36", name: "Tokushima", countryCode: "JP" },
    { code: "37", name: "Kagawa", countryCode: "JP" },
    { code: "38", name: "Ehime", countryCode: "JP" },
    { code: "39", name: "Kochi", countryCode: "JP" },
    { code: "40", name: "Fukuoka", countryCode: "JP" },
    { code: "41", name: "Saga", countryCode: "JP" },
    { code: "42", name: "Nagasaki", countryCode: "JP" },
    { code: "43", name: "Kumamoto", countryCode: "JP" },
    { code: "44", name: "Oita", countryCode: "JP" },
    { code: "45", name: "Miyazaki", countryCode: "JP" },
    { code: "46", name: "Kagoshima", countryCode: "JP" },
    { code: "47", name: "Okinawa", countryCode: "JP" },
  ],
  IT: [
    { code: "ABR", name: "Abruzzo", countryCode: "IT" },
    { code: "BAS", name: "Basilicata", countryCode: "IT" },
    { code: "CAL", name: "Calabria", countryCode: "IT" },
    { code: "CAM", name: "Campania", countryCode: "IT" },
    { code: "EMR", name: "Emilia-Romagna", countryCode: "IT" },
    { code: "FVG", name: "Friuli-Venezia Giulia", countryCode: "IT" },
    { code: "LAZ", name: "Lazio", countryCode: "IT" },
    { code: "LIG", name: "Liguria", countryCode: "IT" },
    { code: "LOM", name: "Lombardy", countryCode: "IT" },
    { code: "MAR", name: "Marche", countryCode: "IT" },
    { code: "MOL", name: "Molise", countryCode: "IT" },
    { code: "PIE", name: "Piedmont", countryCode: "IT" },
    { code: "PUG", name: "Apulia", countryCode: "IT" },
    { code: "SAR", name: "Sardinia", countryCode: "IT" },
    { code: "SIC", name: "Sicily", countryCode: "IT" },
    { code: "TOS", name: "Tuscany", countryCode: "IT" },
    { code: "TRE", name: "Trentino-South Tyrol", countryCode: "IT" },
    { code: "UMB", name: "Umbria", countryCode: "IT" },
    { code: "VAO", name: "Aosta Valley", countryCode: "IT" },
    { code: "VEN", name: "Veneto", countryCode: "IT" },
  ],
  ES: [
    { code: "AN", name: "Andalusia", countryCode: "ES" },
    { code: "AR", name: "Aragon", countryCode: "ES" },
    { code: "AS", name: "Asturias", countryCode: "ES" },
    { code: "CN", name: "Canary Islands", countryCode: "ES" },
    { code: "CB", name: "Cantabria", countryCode: "ES" },
    { code: "CL", name: "Castile and León", countryCode: "ES" },
    { code: "CM", name: "Castilla-La Mancha", countryCode: "ES" },
    { code: "CT", name: "Catalonia", countryCode: "ES" },
    { code: "EX", name: "Extremadura", countryCode: "ES" },
    { code: "GA", name: "Galicia", countryCode: "ES" },
    { code: "IB", name: "Balearic Islands", countryCode: "ES" },
    { code: "RI", name: "La Rioja", countryCode: "ES" },
    { code: "MD", name: "Madrid", countryCode: "ES" },
    { code: "MC", name: "Murcia", countryCode: "ES" },
    { code: "NC", name: "Navarre", countryCode: "ES" },
    { code: "PV", name: "Basque Country", countryCode: "ES" },
    { code: "VC", name: "Valencia", countryCode: "ES" },
  ],
  NL: [
    { code: "DR", name: "Drenthe", countryCode: "NL" },
    { code: "FL", name: "Flevoland", countryCode: "NL" },
    { code: "FR", name: "Friesland", countryCode: "NL" },
    { code: "GE", name: "Gelderland", countryCode: "NL" },
    { code: "GR", name: "Groningen", countryCode: "NL" },
    { code: "LI", name: "Limburg", countryCode: "NL" },
    { code: "NB", name: "North Brabant", countryCode: "NL" },
    { code: "NH", name: "North Holland", countryCode: "NL" },
    { code: "OV", name: "Overijssel", countryCode: "NL" },
    { code: "UT", name: "Utrecht", countryCode: "NL" },
    { code: "ZE", name: "Zeeland", countryCode: "NL" },
    { code: "ZH", name: "South Holland", countryCode: "NL" },
  ],
  SE: [
    { code: "AB", name: "Stockholm", countryCode: "SE" },
    { code: "C", name: "Uppsala", countryCode: "SE" },
    { code: "D", name: "Södermanland", countryCode: "SE" },
    { code: "E", name: "Östergötland", countryCode: "SE" },
    { code: "F", name: "Jönköping", countryCode: "SE" },
    { code: "G", name: "Kronoberg", countryCode: "SE" },
    { code: "H", name: "Kalmar", countryCode: "SE" },
    { code: "I", name: "Gotland", countryCode: "SE" },
    { code: "K", name: "Blekinge", countryCode: "SE" },
    { code: "M", name: "Skåne", countryCode: "SE" },
    { code: "N", name: "Halland", countryCode: "SE" },
    { code: "O", name: "Västra Götaland", countryCode: "SE" },
    { code: "S", name: "Värmland", countryCode: "SE" },
    { code: "T", name: "Örebro", countryCode: "SE" },
    { code: "U", name: "Västmanland", countryCode: "SE" },
    { code: "W", name: "Dalarna", countryCode: "SE" },
    { code: "X", name: "Gävleborg", countryCode: "SE" },
    { code: "Y", name: "Västernorrland", countryCode: "SE" },
    { code: "Z", name: "Jämtland", countryCode: "SE" },
    { code: "AC", name: "Västerbotten", countryCode: "SE" },
    { code: "BD", name: "Norrbotten", countryCode: "SE" },
  ],
  PL: [
    { code: "DS", name: "Lower Silesian", countryCode: "PL" },
    { code: "KP", name: "Kuyavian-Pomeranian", countryCode: "PL" },
    { code: "LU", name: "Lublin", countryCode: "PL" },
    { code: "LB", name: "Lubusz", countryCode: "PL" },
    { code: "LD", name: "Łódź", countryCode: "PL" },
    { code: "MA", name: "Lesser Poland", countryCode: "PL" },
    { code: "MZ", name: "Masovian", countryCode: "PL" },
    { code: "OP", name: "Opole", countryCode: "PL" },
    { code: "PK", name: "Subcarpathian", countryCode: "PL" },
    { code: "PD", name: "Podlaskie", countryCode: "PL" },
    { code: "PM", name: "Pomeranian", countryCode: "PL" },
    { code: "SL", name: "Silesian", countryCode: "PL" },
    { code: "SK", name: "Świętokrzyskie", countryCode: "PL" },
    { code: "WN", name: "Warmian-Masurian", countryCode: "PL" },
    { code: "WP", name: "Greater Poland", countryCode: "PL" },
    { code: "ZP", name: "West Pomeranian", countryCode: "PL" },
  ],
  AR: [
    { code: "BA", name: "Buenos Aires", countryCode: "AR" },
    { code: "CF", name: "Capital Federal", countryCode: "AR" },
    { code: "CT", name: "Catamarca", countryCode: "AR" },
    { code: "CH", name: "Chaco", countryCode: "AR" },
    { code: "CB", name: "Chubut", countryCode: "AR" },
    { code: "CO", name: "Córdoba", countryCode: "AR" },
    { code: "CR", name: "Corrientes", countryCode: "AR" },
    { code: "ER", name: "Entre Ríos", countryCode: "AR" },
    { code: "FO", name: "Formosa", countryCode: "AR" },
    { code: "JY", name: "Jujuy", countryCode: "AR" },
    { code: "LP", name: "La Pampa", countryCode: "AR" },
    { code: "LR", name: "La Rioja", countryCode: "AR" },
    { code: "MZ", name: "Mendoza", countryCode: "AR" },
    { code: "MI", name: "Misiones", countryCode: "AR" },
    { code: "NQ", name: "Neuquén", countryCode: "AR" },
    { code: "RN", name: "Río Negro", countryCode: "AR" },
    { code: "SA", name: "Salta", countryCode: "AR" },
    { code: "SJ", name: "San Juan", countryCode: "AR" },
    { code: "SL", name: "San Luis", countryCode: "AR" },
    { code: "SC", name: "Santa Cruz", countryCode: "AR" },
    { code: "SF", name: "Santa Fe", countryCode: "AR" },
    { code: "SE", name: "Santiago del Estero", countryCode: "AR" },
    { code: "TF", name: "Tierra del Fuego", countryCode: "AR" },
    { code: "TM", name: "Tucumán", countryCode: "AR" },
  ],
};

// Sample cities data (this would ideally come from an API)
export const citiesData: Record<string, City[]> = {
  "US-CA": [
    { name: "Los Angeles", stateCode: "CA", countryCode: "US" },
    { name: "San Francisco", stateCode: "CA", countryCode: "US" },
    { name: "San Diego", stateCode: "CA", countryCode: "US" },
    { name: "San Jose", stateCode: "CA", countryCode: "US" },
    { name: "Sacramento", stateCode: "CA", countryCode: "US" },
  ],
  "US-NY": [
    { name: "New York City", stateCode: "NY", countryCode: "US" },
    { name: "Buffalo", stateCode: "NY", countryCode: "US" },
    { name: "Rochester", stateCode: "NY", countryCode: "US" },
    { name: "Albany", stateCode: "NY", countryCode: "US" },
  ],
  "US-TX": [
    { name: "Houston", stateCode: "TX", countryCode: "US" },
    { name: "Dallas", stateCode: "TX", countryCode: "US" },
    { name: "Austin", stateCode: "TX", countryCode: "US" },
    { name: "San Antonio", stateCode: "TX", countryCode: "US" },
  ],
  "US-FL": [
    { name: "Miami", stateCode: "FL", countryCode: "US" },
    { name: "Orlando", stateCode: "FL", countryCode: "US" },
    { name: "Tampa", stateCode: "FL", countryCode: "US" },
    { name: "Jacksonville", stateCode: "FL", countryCode: "US" },
  ],
  "CA-ON": [
    { name: "Toronto", stateCode: "ON", countryCode: "CA" },
    { name: "Ottawa", stateCode: "ON", countryCode: "CA" },
    { name: "Mississauga", stateCode: "ON", countryCode: "CA" },
  ],
  "CA-BC": [
    { name: "Vancouver", stateCode: "BC", countryCode: "CA" },
    { name: "Victoria", stateCode: "BC", countryCode: "CA" },
  ],
  "GB-ENG": [
    { name: "London", stateCode: "ENG", countryCode: "GB" },
    { name: "Manchester", stateCode: "ENG", countryCode: "GB" },
    { name: "Birmingham", stateCode: "ENG", countryCode: "GB" },
    { name: "Liverpool", stateCode: "ENG", countryCode: "GB" },
  ],
  "IN-MH": [
    { name: "Mumbai", stateCode: "MH", countryCode: "IN" },
    { name: "Pune", stateCode: "MH", countryCode: "IN" },
    { name: "Nagpur", stateCode: "MH", countryCode: "IN" },
  ],
  "IN-DL": [
    { name: "New Delhi", stateCode: "DL", countryCode: "IN" },
  ],
  "IN-KA": [
    { name: "Bangalore", stateCode: "KA", countryCode: "IN" },
    { name: "Mysore", stateCode: "KA", countryCode: "IN" },
  ],
  "AU-NSW": [
    { name: "Sydney", stateCode: "NSW", countryCode: "AU" },
    { name: "Newcastle", stateCode: "NSW", countryCode: "AU" },
  ],
  "AU-VIC": [
    { name: "Melbourne", stateCode: "VIC", countryCode: "AU" },
  ],
  "AU-QLD": [
    { name: "Brisbane", stateCode: "QLD", countryCode: "AU" },
    { name: "Gold Coast", stateCode: "QLD", countryCode: "AU" },
  ],
  
  // Germany Cities
  "DE-BE": [
    { name: "Berlin", stateCode: "BE", countryCode: "DE" },
  ],
  "DE-BY": [
    { name: "Munich", stateCode: "BY", countryCode: "DE" },
    { name: "Nuremberg", stateCode: "BY", countryCode: "DE" },
  ],
  "DE-HH": [
    { name: "Hamburg", stateCode: "HH", countryCode: "DE" },
  ],
  "DE-NW": [
    { name: "Cologne", stateCode: "NW", countryCode: "DE" },
    { name: "Dusseldorf", stateCode: "NW", countryCode: "DE" },
    { name: "Dortmund", stateCode: "NW", countryCode: "DE" },
  ],
  "DE-HE": [
    { name: "Frankfurt", stateCode: "HE", countryCode: "DE" },
  ],
  
  // France Cities
  "FR-IDF": [
    { name: "Paris", stateCode: "IDF", countryCode: "FR" },
    { name: "Versailles", stateCode: "IDF", countryCode: "FR" },
  ],
  "FR-ARA": [
    { name: "Lyon", stateCode: "ARA", countryCode: "FR" },
    { name: "Grenoble", stateCode: "ARA", countryCode: "FR" },
  ],
  "FR-PAC": [
    { name: "Marseille", stateCode: "PAC", countryCode: "FR" },
    { name: "Nice", stateCode: "PAC", countryCode: "FR" },
  ],
  
  // Brazil Cities
  "BR-SP": [
    { name: "São Paulo", stateCode: "SP", countryCode: "BR" },
    { name: "Campinas", stateCode: "SP", countryCode: "BR" },
  ],
  "BR-RJ": [
    { name: "Rio de Janeiro", stateCode: "RJ", countryCode: "BR" },
    { name: "Niterói", stateCode: "RJ", countryCode: "BR" },
  ],
  "BR-MG": [
    { name: "Belo Horizonte", stateCode: "MG", countryCode: "BR" },
  ],
  "BR-BA": [
    { name: "Salvador", stateCode: "BA", countryCode: "BR" },
  ],
  "BR-DF": [
    { name: "Brasília", stateCode: "DF", countryCode: "BR" },
  ],
  
  // Mexico Cities
  "MX-CMX": [
    { name: "Mexico City", stateCode: "CMX", countryCode: "MX" },
  ],
  "MX-JAL": [
    { name: "Guadalajara", stateCode: "JAL", countryCode: "MX" },
  ],
  "MX-NLE": [
    { name: "Monterrey", stateCode: "NLE", countryCode: "MX" },
  ],
  "MX-PUE": [
    { name: "Puebla", stateCode: "PUE", countryCode: "MX" },
  ],
  
  // China Cities
  "CN-BJ": [
    { name: "Beijing", stateCode: "BJ", countryCode: "CN" },
  ],
  "CN-SH": [
    { name: "Shanghai", stateCode: "SH", countryCode: "CN" },
  ],
  "CN-GD": [
    { name: "Guangzhou", stateCode: "GD", countryCode: "CN" },
    { name: "Shenzhen", stateCode: "GD", countryCode: "CN" },
  ],
  "CN-ZJ": [
    { name: "Hangzhou", stateCode: "ZJ", countryCode: "CN" },
  ],
  "CN-SC": [
    { name: "Chengdu", stateCode: "SC", countryCode: "CN" },
  ],
  
  // Japan Cities
  "JP-13": [
    { name: "Tokyo", stateCode: "13", countryCode: "JP" },
  ],
  "JP-27": [
    { name: "Osaka", stateCode: "27", countryCode: "JP" },
  ],
  "JP-26": [
    { name: "Kyoto", stateCode: "26", countryCode: "JP" },
  ],
  "JP-14": [
    { name: "Yokohama", stateCode: "14", countryCode: "JP" },
  ],
  "JP-01": [
    { name: "Sapporo", stateCode: "01", countryCode: "JP" },
  ],
  
  // Italy Cities
  "IT-LAZ": [
    { name: "Rome", stateCode: "LAZ", countryCode: "IT" },
  ],
  "IT-LOM": [
    { name: "Milan", stateCode: "LOM", countryCode: "IT" },
  ],
  "IT-CAM": [
    { name: "Naples", stateCode: "CAM", countryCode: "IT" },
  ],
  "IT-TOS": [
    { name: "Florence", stateCode: "TOS", countryCode: "IT" },
  ],
  "IT-VEN": [
    { name: "Venice", stateCode: "VEN", countryCode: "IT" },
  ],
  
  // Spain Cities
  "ES-MD": [
    { name: "Madrid", stateCode: "MD", countryCode: "ES" },
  ],
  "ES-CT": [
    { name: "Barcelona", stateCode: "CT", countryCode: "ES" },
  ],
  "ES-AN": [
    { name: "Seville", stateCode: "AN", countryCode: "ES" },
    { name: "Malaga", stateCode: "AN", countryCode: "ES" },
  ],
  "ES-VC": [
    { name: "Valencia", stateCode: "VC", countryCode: "ES" },
  ],
  
  // Netherlands Cities
  "NL-NH": [
    { name: "Amsterdam", stateCode: "NH", countryCode: "NL" },
  ],
  "NL-ZH": [
    { name: "Rotterdam", stateCode: "ZH", countryCode: "NL" },
    { name: "The Hague", stateCode: "ZH", countryCode: "NL" },
  ],
  "NL-UT": [
    { name: "Utrecht", stateCode: "UT", countryCode: "NL" },
  ],
  
  // Sweden Cities
  "SE-AB": [
    { name: "Stockholm", stateCode: "AB", countryCode: "SE" },
  ],
  "SE-O": [
    { name: "Gothenburg", stateCode: "O", countryCode: "SE" },
  ],
  "SE-M": [
    { name: "Malmö", stateCode: "M", countryCode: "SE" },
  ],
  
  // Poland Cities
  "PL-MZ": [
    { name: "Warsaw", stateCode: "MZ", countryCode: "PL" },
  ],
  "PL-MA": [
    { name: "Krakow", stateCode: "MA", countryCode: "PL" },
  ],
  "PL-DS": [
    { name: "Wroclaw", stateCode: "DS", countryCode: "PL" },
  ],
  
  // Argentina Cities
  "AR-CF": [
    { name: "Buenos Aires", stateCode: "CF", countryCode: "AR" },
  ],
  "AR-CO": [
    { name: "Córdoba", stateCode: "CO", countryCode: "AR" },
  ],
  "AR-SF": [
    { name: "Rosario", stateCode: "SF", countryCode: "AR" },
  ],
};

// API functions
export const locationAPI = {
  // Get all countries
  getCountries: (): Country[] => {
    return popularCountries;
  },

  // Search countries by name
  searchCountries: (query: string): Country[] => {
    if (!query) return popularCountries;
    const lowerQuery = query.toLowerCase();
    return popularCountries.filter(country =>
      country.name.toLowerCase().includes(lowerQuery)
    );
  },

  // Get states for selected countries
  getStatesForCountries: (countryCodes: string[]): State[] => {
    const states: State[] = [];
    countryCodes.forEach(code => {
      if (statesData[code]) {
        states.push(...statesData[code]);
      }
    });
    return states;
  },

  // Search states
  searchStates: (countryCodes: string[], query: string): State[] => {
    const allStates = locationAPI.getStatesForCountries(countryCodes);
    if (!query) return allStates;
    const lowerQuery = query.toLowerCase();
    return allStates.filter(state =>
      state.name.toLowerCase().includes(lowerQuery)
    );
  },

  // Get cities for selected states
  getCitiesForStates: (stateKeys: string[]): City[] => {
    const cities: City[] = [];
    stateKeys.forEach(key => {
      if (citiesData[key]) {
        cities.push(...citiesData[key]);
      }
    });
    return cities;
  },

  // Search cities
  searchCities: (stateKeys: string[], query: string): City[] => {
    const allCities = locationAPI.getCitiesForStates(stateKeys);
    if (!query) return allCities;
    const lowerQuery = query.toLowerCase();
    return allCities.filter(city =>
      city.name.toLowerCase().includes(lowerQuery)
    );
  },
};
